name: test_autumn

trajectories_path: /sc/home/tim.riedel/masterthesis/assets/datasets/EDDB-test-autumn/trajectories/EDDB_trajectories-resampled_2024-10-21_2024-10-30.parquet
scenes_path: /sc/home/tim.riedel/masterthesis/assets/datasets/EDDB-test-autumn/trajectories/EDDB_trajectories-scenes_2024-10-21_2024-10-30.parquet
flightinfo_path: /sc/home/tim.riedel/masterthesis/assets/datasets/EDDB-test-autumn/flightinfo/EDDB_flightinfo_2024-10-21_2024-10-30.parquet

input_time_minutes: 5
horizon_time_minutes: 40
resampling_rate_seconds: 30

k_folds: 1
cross_val_fold_idx: 0
