defaults:
  - base_config
  - model: agentformer
  - features: aerion
  - dataset: single_day
  - _self_

# --------------------------------------
# Overrides
# --------------------------------------

experiment_name: "debug-agentformer-aerion"

execution:
  multi_agent_prediction: true

trainer:
  max_epochs: 40

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 0.01

scheduler:
  warmup_epochs: 5

dataloader:
  batch_size: 350
